### ISSUE TITLE
tick() never fires update

### ISSUE THREAD

**Issue by dm56-09** [GyverLibs/EEManager#2]
_update variable permitting tick() is never set to true in code. Actually, it is never needed.

**Comment by GyverLibs** [comment]
```cpp
// отложить обновление и сбросить таймер
    void update() {
        _tmr = millis();
        _update = 1;   // am i joke to you?
    }
    
    // тикер обновления
    bool tick() {
        if (_update && millis() - _tmr >= _tout) {
            updateNow();
            _update = 0;
            return 1;
        } return 0;
    }
```

**Comment by dm56-09** [comment]
> _update variable permitting tick() is never set to true in code. Actually, it is never needed.

update() where _update is set is never called in tick().

**Comment by dm56-09** [comment]
I spent some time testing my code where tick() did nothing before bothering Your Majesty

**Comment by dm56-09** [comment]
This stuff works OK:

class EEManager {
public:
    template <typename T> EEManager(T &data, uint16_t tout = 5000) // передать данные любого типа, опционально таймаут обновления в мс
    {
      _data = (uint8_t*) &data;
      _size = sizeof(T);
      _tout = tout;
    }
    
    void setTimeout(uint16_t tout = 5000) { _tout = tout; } // сменить таймаут
    
    uint8_t begin(uint8_t addr, uint8_t key) // начать работу, прочитать данные в переменную. Принимает адрес начала хранения даты и ключ
    {        
      _addr = addr;
      if (_addr + _size + 1 > (uint16_t) EEPROM.length()) 
        return 2;  // не хватит места
      _ready = true;
      if (EEPROM.read(_addr + _size) != key) // ключ не совпал
      {            
        EEPROM.write(_addr + _size, key);               // пишем ключ
        updateNow();                                    // пишем стандартные значения
        return 1;
      }
      for (uint16_t i = 0; i < _size; i++) _data[i] = EEPROM.read(_addr + i);
      return 0;
    }
    
    void updateNow()  // обновить данные в еепром сейчас
    {
      if (_ready) 
      {            
#if defined(ESP8266) || defined(ESP32)
        for (uint16_t i = 0; i < _size; i++) EEPROM.write(_addr + i, _data[i]);
        EEPROM.commit();
#else
        for (uint16_t i = 0; i < _size; i++) EEPROM.update(_addr + i, _data[i]);
#endif
      }
      _tmr = millis();
    }
    
    bool tick() // тикер обновления
    {
      if (millis() - _tmr >= _tout) 
      {
        updateNow();
        return true;
      } 
      return false;
    }
    
    void reset() // сбросить ключ запуска. При перезагрузке (или вызове begin) запишутся стандартные данные 
    {
      EEPROM.write(_addr + _size, EEPROM.read(_addr + _size) + 1);   // меняем ключ на +1, при перезапуске будет дефолт
    }
    
    uint16_t dataSize() { return _size; } // получить размер данных
    uint16_t blockSize() { return _size + 1; } // получить размер всего блока (данные + ключ)
    
    // получить адрес первого байта в блоке
    uint16_t startAddr() { return _addr; }
    
    // получить адрес последнего байта в блоке (включая ключ)
    uint16_t endAddr() { return _addr + _size; }
    
    // получить первый свободный адрес для следующего блока
    uint16_t nextAddr() { return _addr + _size + 1; }

private:
    uint8_t* _data;
    uint16_t _size, _addr;
    bool _ready = false;
    uint32_t _tmr = 0;
    uint16_t _tout;
};

**Comment by GyverLibs** [comment]
> update() where _update is set is never called in tick()

Of course. Watch an example

**Comment by GyverLibs** [comment]
> This stuff works OK:

This stuff isn't correct at all

**Comment by GyverLibs** [comment]
This library works as:
- You call `tick()` in main loop
- When you need data to update - call `update()`. Data will be automatically update inside `tick()` after timeout
- It is safe to call `update()` many times in code. This action will not wear eeprom because of timeout

**Comment by dm56-09** [comment]
OK, then some misunderstanding took place. I loosely thought that tick() is enough to make everything work properly as in other tick()ers of yours - like encButton etc. "NEVER MAKE ASSUMPTIONS" LOL. BTW, what's wrong with the src I've sent here? At least, it works as expected.

**Comment by dm56-09** [comment]
Anyway, I apologize for your wasted time. Have a nice day.

**Comment by GyverLibs** [comment]
> what's wrong with the src I've sent here?

Your code just rewrites EEPROM every _tout milliseconds. So library becomes usless, you can just use EEPROM.put(ur_data) inside millis-timer. And your flash will be weared soon ;)

**Comment by dm56-09** [comment]
In case of non-ESP it does nothing if written data is same

**Comment by dm56-09** [comment]
"the same" sorry

**Comment by dm56-09** [comment]
Would be great to move blocks automatically through avalable EEPROM space, thus reducing wearing & tearing :)

**Comment by GyverLibs** [comment]
> non-ESP

So what should esp users do? It doesn't make sense, just periodically re-update memory, spending processor time for dumb work

**Comment by dm56-09** [comment]
Let ESP's put updates() everywhere :) 
Suppose I have a lot of places where block is modified. A lot of unneeded update()'s should be inserted into code then where arduino makes update() itself. In case of pure tick() I get beautiful code with the same result.

**Comment by dm56-09** [comment]
Ok, did this way:

Set Commander;
enum { NEED_UPDATE } ;
loop()
{
   MySavedStruct::xxxx++;              |// Many times many vars many places
   Commander << NEED_UPDATE; |// damn fast

.................................................................................................
   if (Commander.Kill(NEED_UPDATE))
   {
     Eepromer.update();
     Eepromer.tick();
   }
}

Still not as perfect as pure tick() without extra rambling.

**Comment by GyverLibs** [comment]
you can call `updateNow()` when you want and don't use tick() in code at all

**Comment by GyverLibs** [comment]
> A lot of unneeded update()'s should be inserted into code 

Bruh, just put `.updateNow()` directly in `loop()`. You dont need `tick()` at all

> then where arduino makes update() itself

Arduino AVR framework - yes. Arduino ESP framework - no. Library is not for AVR, it is for all Arduino.
