### ISSUE TITLE
ESP32 ошибка при инициализации (не хватает места)

### ISSUE THREAD

**Issue by mqstarx** [GyverLibs/EEManager#3]
// if (_addr + _size + 1 > (uint16_t)EEPROM.length()) return 2;  // не хватит места

необходимо комментировать строку в файле EEManager.h т.к EEPROM.length() ничего не выдает

**Comment by GyverLibs** [comment]
Ой да в жеппу эту есп 32! Где ни глянь, дыра или несовместимость...

**Comment by GyverLibs** [comment]
`lenght()` работает корректно
```cpp
#include <EEPROM.h>
void setup() {
  Serial.begin(115200);
  EEPROM.begin(400);
  delay(3000);
  Serial.println(EEPROM.length());  // вывод 400
}

void loop() {
}
```

- Либо у вас слишком старая версия ядра
- Либо аппаратные проблемы
- Либо забыт `EEPROM.begin()`, см. самое начало [README](https://github.com/GyverLibs/EEManager#%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C)

**Comment by mqstarx** [comment]
Спасибо за отклик. Попробую на другой железке.

вт, 24 янв. 2023 г., 20:54 AlexGyver ***@***.***>:
